info:
  name: Product Master - Update
  type: http
  seq: 4

http:
  method: PATCH
  url: "{{baseUrl}}/product-master/3"
  headers:
    - name: Content-Type
      value: application/json
    - name: Authorization
      value: Bearer {{accessToken}}
  body:
    type: json
    data: |-
      {
        "version": 1,
        "productCode": "PROD03",
        "productName": "Updated Product Name",
        "productType": "DOMESTIC",
        "fuelCharge": false,
        "gstReverse": false,
        "docType": "DOX",
        "status": "ACTIVE",
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: |-
  Product Master update by id. JWT + product_master_modify or product_master_all.

  Mandatory: version
  Optional: productCode, productName, productType, productService, fuelCharge, gstReverse, docType, status, groupType
