info:
  name: Update Role
  type: http
  seq: 4

http:
  method: PATCH
  url: "{{baseUrl}}/utilities/roles/{{roleId}}"
  headers:
    - name: Content-Type
      value: application/json
    - name: Authorization
      value: Bearer {{accessToken}}
  body:
    type: json
    data: |-
      {
        "name": "Operations Manager Updated",
        "identifier": "operations_manager",
        "description": "Updated role description",
        "permissionIds": [1, 2, 3, 4]
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
